[default.general]
chip = "STM32F103C8" # uncomment this line for micro:bit V2

[default.reset]
halt_afterwards = false

[default.rtt]
enabled = true

[default.gdb]
enabled = false

[default.probe]
protocol = "Swd"
